--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VIEW_FACTURAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LUIS"."VIEW_FACTURAS" ("NFACTURA", "FECFACTURA", "CODCLIENTE") AS 
  SELECT NFACTURA, FECFACTURA, CODCLIENTE FROM FACTURAS
;
--------------------------------------------------------
--  DDL for View VIEW_FACTURAS_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LUIS"."VIEW_FACTURAS_CLIENTES" ("NFACTURA", "FECFACTURA", "CODCLIENTE", "NOMBRE", "PAGADA") AS 
  SELECT NFACTURA, FECFACTURA, CODCLIENTE, NOMBRE, PAGADA FROM FACTURAS INNER JOIN CLIENTES ON FACTURAS.CODCLIENTE = CLIENTES.CODIGO
;
--------------------------------------------------------
--  DDL for View VIEW_LINFACTURA_ARTICULO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LUIS"."VIEW_LINFACTURA_ARTICULO" ("ID", "NFACTURA", "REFERENCIA", "CANTIDAD", "DESCRIPCION", "PRECIO", "DESCUENTO", "SUBTOTAL") AS 
  SELECT ID,NFACTURA, LINFACTURAS.REFERENCIA, CANTIDAD, DESCRIPCION, PRECIO, DESCUENTO,PRECIO*CANTIDAD-DESCUENTO AS SUBTOTAL  FROM LINFACTURAS INNER JOIN ARTICULOS ON LINFACTURAS.REFERENCIA = ARTICULOS.REFERENCIA
;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "LUIS"."ARTICULOS" 
   (	"REFERENCIA" VARCHAR2(13 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"STOCK" NUMBER(10,2), 
	"PRECIO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "LUIS"."CLIENTES" 
   (	"CODIGO" NUMBER(10,0), 
	"DNI" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"FECNAC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURAS
--------------------------------------------------------

  CREATE TABLE "LUIS"."FACTURAS" 
   (	"NFACTURA" NUMBER(10,0), 
	"FECFACTURA" DATE, 
	"CODCLIENTE" NUMBER(10,0), 
	"TOTAL" NUMBER(12,2), 
	"PAGADA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINFACTURAS
--------------------------------------------------------

  CREATE TABLE "LUIS"."LINFACTURAS" 
   (	"ID" NUMBER(10,0), 
	"NFACTURA" NUMBER(10,0), 
	"REFERENCIA" VARCHAR2(13 BYTE), 
	"CANTIDAD" NUMBER(10,2), 
	"DESCUENTO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "LUIS"."USUARIOS" 
   (	"NOMBRE" VARCHAR2(150 BYTE), 
	"PASS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LUIS.ARTICULOS
SET DEFINE OFF;
Insert into LUIS.ARTICULOS (REFERENCIA,DESCRIPCION,STOCK,PRECIO) values ('pr1','Monitor','74','159');
Insert into LUIS.ARTICULOS (REFERENCIA,DESCRIPCION,STOCK,PRECIO) values ('pr5','Caja PC','26','150');
Insert into LUIS.ARTICULOS (REFERENCIA,DESCRIPCION,STOCK,PRECIO) values ('pr4','Teclado','150','65');
Insert into LUIS.ARTICULOS (REFERENCIA,DESCRIPCION,STOCK,PRECIO) values ('pr3','Raton','26','400');
Insert into LUIS.ARTICULOS (REFERENCIA,DESCRIPCION,STOCK,PRECIO) values ('pr7','Toshiba portatil','150','480');
REM INSERTING into LUIS.CLIENTES
SET DEFINE OFF;
Insert into LUIS.CLIENTES (CODIGO,DNI,NOMBRE,FECNAC) values ('1','76654212-F','Luis',to_date('25/10/17','DD/MM/RR'));
Insert into LUIS.CLIENTES (CODIGO,DNI,NOMBRE,FECNAC) values ('3','69584532-R','Francisco jose',to_date('06/10/17','DD/MM/RR'));
Insert into LUIS.CLIENTES (CODIGO,DNI,NOMBRE,FECNAC) values ('6','6543219-A','Manolo',to_date('19/05/78','DD/MM/RR'));
REM INSERTING into LUIS.FACTURAS
SET DEFINE OFF;
Insert into LUIS.FACTURAS (NFACTURA,FECFACTURA,CODCLIENTE,TOTAL,PAGADA) values ('1',to_date('26/10/17','DD/MM/RR'),'1','0','N');
REM INSERTING into LUIS.LINFACTURAS
SET DEFINE OFF;
Insert into LUIS.LINFACTURAS (ID,NFACTURA,REFERENCIA,CANTIDAD,DESCUENTO) values ('1','1','pr1','12','11');
REM INSERTING into LUIS.USUARIOS
SET DEFINE OFF;
Insert into LUIS.USUARIOS (NOMBRE,PASS) values ('luis','luis');
Insert into LUIS.USUARIOS (NOMBRE,PASS) values ('pepe','pepe');
--------------------------------------------------------
--  DDL for Trigger TR_DELETE_LINFAC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LUIS"."TR_DELETE_LINFAC" 
AFTER DELETE ON Linfacturas
FOR EACH ROW 
BEGIN 

UPDATE ARTICULOS SET STOCK= STOCK + :OLD.CANTIDAD WHERE REFERENCIA = :OLD.referencia;

END;
/
ALTER TRIGGER "LUIS"."TR_DELETE_LINFAC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_LINFAC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LUIS"."TR_INSERT_LINFAC" 
AFTER INSERT ON Linfacturas
FOR EACH ROW 
BEGIN 

UPDATE ARTICULOS SET STOCK= STOCK - :NEW.CANTIDAD WHERE REFERENCIA = :NEW.referencia;

END;
/
ALTER TRIGGER "LUIS"."TR_INSERT_LINFAC" ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."USUARIOS" ADD PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LUIS"."USUARIOS" MODIFY ("PASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "LUIS"."ARTICULOS" ADD PRIMARY KEY ("REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."FACTURAS" ADD PRIMARY KEY ("NFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LINFACTURAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."LINFACTURAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "LUIS"."CLIENTES" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."FACTURAS" ADD CONSTRAINT "FK_CLIENTES_FACTURAS" FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "LUIS"."CLIENTES" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINFACTURAS
--------------------------------------------------------

  ALTER TABLE "LUIS"."LINFACTURAS" ADD CONSTRAINT "FK_ARTICULOS_LINFAC" FOREIGN KEY ("REFERENCIA")
	  REFERENCES "LUIS"."ARTICULOS" ("REFERENCIA") ENABLE;
  ALTER TABLE "LUIS"."LINFACTURAS" ADD CONSTRAINT "FK_FACTURAS_LINFAC" FOREIGN KEY ("NFACTURA")
	  REFERENCES "LUIS"."FACTURAS" ("NFACTURA") ENABLE;
